model_provider = "oaiapi"
model = "gpt-5.4"
model_reasoning_effort = "xhigh"
model_context_window = 900000
model_auto_compact_token_limit = 850000
approval_policy = "never"
sandbox_mode = "danger-full-access"
network_access = "enabled"
disable_response_storage = true
windows_wsl_setup_acknowledged = true
model_verbosity = "high"
personality = "friendly"
plan_mode_reasoning_effort = "xhigh"
service_tier = "fast"

[model_providers.oaiapi]
name = "oaiapi"
base_url = "https://api1.oai1.online/v1"
wire_api = "responses"
requires_openai_auth = true

[windows]
sandbox = "elevated"

[projects."/home/czc/projects/working/test/math_phy"]
trust_level = "trusted"

[projects."/home/czc"]
trust_level = "trusted"

[projects."/home/czc/projects/working/git_intro"]
trust_level = "trusted"

[projects."/home/czc/projects/done/Backups"]
trust_level = "trusted"

[projects."/home/czc/projects/working/math_phy"]
trust_level = "trusted"

[projects."/home/czc/projects/working/translation/test"]
trust_level = "trusted"

[projects."/home/czc/projects/working/test/test2"]
trust_level = "trusted"

[projects."/home/czc/projects/working/test/test3"]
trust_level = "trusted"

[projects."/home/czc/projects/working/gpd_tutorial"]
trust_level = "trusted"

[projects."/home/czc/project/working/test/you"]
trust_level = "trusted"

[projects."/home/czc/project/working/test/ps2"]
trust_level = "trusted"

[projects."/home/czc/project/working/test/ps"]
trust_level = "trusted"

[projects."/home/czc/mirror"]
trust_level = "trusted"

[projects."/home/czc/youwu"]
trust_level = "trusted"

[features]
multi_agent = true
plugins = false
