model_provider = "OpenAI"
model = "gpt-5.5"
model_reasoning_effort = "xhigh"
approval_policy = "never"
sandbox_mode = "danger-full-access"
network_access = "enabled"
disable_response_storage = true
windows_wsl_setup_acknowledged = true
model_verbosity = "medium"
personality = "friendly"
plan_mode_reasoning_effort = "xhigh"
tool_output_token_limit = 8000

[model_providers.OpenAI]
name = "oaiapi"
base_url = "https://mofa.love.gd"
wire_api = "responses"
requires_openai_auth = true
request_max_retries = 10
stream_max_retries = 10
stream_idle_timeout_ms = 600000

[windows]
sandbox = "elevated"

[tui]
 status_line = [
    "model-with-reasoning",
    "current-dir",
    "git-branch",
    "used-tokens",
    "context-window-size",
  ]

[tui.model_availability_nux]
"gpt-5.5" = 4

[projects."/home/czc/projects/working/test/math_phy"]
trust_level = "trusted"

[projects."/home/czc"]
trust_level = "trusted"

[projects."/home/czc/projects/working/git_intro"]
trust_level = "trusted"

[projects."/home/czc/projects/done/Backups"]
trust_level = "trusted"

[projects."/home/czc/projects/working/math_phy"]
trust_level = "trusted"

[projects."/home/czc/projects/working/translation/test"]
trust_level = "trusted"

[projects."/home/czc/projects/working/test/test2"]
trust_level = "trusted"

[projects."/home/czc/.codex"]
trust_level = "trusted"

[projects."/home/czc/projects/working/math_phy_solution"]
trust_level = "trusted"

[projects."/home/czc/projects/working/massive_gravity_orf"]
trust_level = "trusted"

[projects."/home/czc/Downloads/test/test/main"]
trust_level = "trusted"

[projects."/home/czc/projects/working/gpd_tutorial"]
trust_level = "trusted"

[projects."/home/czc/projects/working/translation/systematic_trading"]
trust_level = "trusted"

[projects."/home/czc/projects/working/codex_cli_guide"]
trust_level = "trusted"

[projects."/home/czc/projects/working/pta/massive_gravity_orf"]
trust_level = "trusted"

[projects."/home/czc/projects/working/gpd_projects/massive_gravity_orf"]
trust_level = "trusted"

[projects."/home/czc/projects/working/gpd_projects/GW_energy_massive_gravity_general_background"]
trust_level = "trusted"

[projects."/home/czc/projects/working/gpd_projects/fT_massive_gravity"]
trust_level = "trusted"

[projects."/home/czc/projects/working/Lean/2603.08139"]
trust_level = "trusted"

[projects."/home/czc/Downloads/test"]
trust_level = "trusted"

[projects."/home/czc/projects/working/gpd_projects/GR_ORF"]
trust_level = "trusted"

[projects."/home/czc/projects/working/translation/Cosmology_Daniel"]
trust_level = "trusted"

[projects."/home/czc/projects/working/gwtc-4/qg_gwtc4"]
trust_level = "trusted"

[projects."/home/czc/projects/working/gpt_reg"]
trust_level = "trusted"

[projects."/home/czc/Downloads/X6.5-Linux版"]
trust_level = "trusted"

[projects."/home/czc/projects/working/sub2api"]
trust_level = "trusted"

[projects."/home/czc/projects/working/Codex-Manager"]
trust_level = "trusted"

[projects."/home/czc/projects/working/X6.5-Linux"]
trust_level = "trusted"

[projects."/home/czc/projects/working/test"]
trust_level = "trusted"

[projects."/home/czc/projects/working/pbh/merger_history_GWTC3/code"]
trust_level = "trusted"

[projects."/home/czc/projects/working/pbh/merger_history_GWTC3"]
trust_level = "trusted"

[projects."/home/czc/projects/working/gwtc-4/pbh_merger_history_gwtc4"]
trust_level = "trusted"

[projects."/home/czc/Downloads/test/review"]
trust_level = "trusted"

[projects."/home/czc/projects/working/codex_reg/xianyu"]
trust_level = "trusted"

[projects."/home/czc/projects/working/codex_reg/xianyu_codex_reg"]
trust_level = "trusted"

[projects."/home/czc/projects/working"]
trust_level = "trusted"

[projects."/home/czc/Downloads/test/CSB-2026-0428"]
trust_level = "trusted"

[projects."/home/czc/projects/working/codex_reg/X7.1-iCloud分身普号注册机"]
trust_level = "trusted"

[projects."/home/czc/projects/working/codex_reg/X7.1-iCloud分身普号注册机/X7"]
trust_level = "trusted"

[projects."/home/czc/projects/working/cloudflare_temp_email"]
trust_level = "trusted"

[projects."/home/czc/projects/working/KiroProxy"]
trust_level = "trusted"

[projects."/home/czc/projects/done/Linux_Setting"]
trust_level = "trusted"

[projects."/home/czc/projects/working/translation/QM_Shankar"]
trust_level = "trusted"

[projects."/home/czc/projects/working/translation/complex_variables_and_applications"]
trust_level = "trusted"

[projects."/home/czc/projects/working/translation/QFT_Anthony"]
trust_level = "trusted"

[projects."/home/czc/projects/working/translation/differential_quations_demystified"]
trust_level = "trusted"

[projects."/home/czc/projects/working/translation/General Relativity-An Introduction for Physicists"]
trust_level = "trusted"

[projects."/home/czc/projects/working/gwtc5"]
trust_level = "trusted"

[projects."/home/czc/projects/working/gwtc4/SGWB"]
trust_level = "trusted"

[projects."/home/czc/projects/working/gwtc4"]
trust_level = "trusted"

[projects."/home/czc/projects/working/wan2gp"]
trust_level = "trusted"

[projects."/home/czc/projects/working/Qwen"]
trust_level = "trusted"

[projects."/home/czc/Downloads/test/team/20260608-075429-83bb7393 (1)"]
trust_level = "trusted"

[projects."/home/czc/projects/working/Taiji"]
trust_level = "trusted"

[projects."/home/czc/projects/working/codex_reg/chatgpt-team-register"]
trust_level = "trusted"

[projects."/home/czc/projects/working/stock/KLineForge"]
trust_level = "trusted"

[projects."/home/czc/projects/working/dynesty.jl"]
trust_level = "trusted"

[projects."/home/czc/Documents/Codex/2026-06-10/hi"]
trust_level = "trusted"

[projects."/home/czc/projects/working/Icarogw.jl"]
trust_level = "trusted"

[projects."/home/czc/projects/working/Dynesty.jl"]
trust_level = "trusted"

[projects."/home/czc/Downloads/temp"]
trust_level = "trusted"

[projects."/home/czc/projects/working/goal-workflow"]
trust_level = "trusted"

[projects."/home/czc/projects/working/qft_from_caculus"]
trust_level = "trusted"

[projects."/home/czc/Documents/Codex/2026-06-24/hi"]
trust_level = "trusted"

[projects."/home/czc/Documents/Codex/2026-06-25/hi"]
trust_level = "trusted"

[projects."/home/czc/Documents/Codex/2026-06-25/codex-desktop"]
trust_level = "trusted"

[projects."/home/czc/projects/working/zuchengchen.github.io"]
trust_level = "trusted"

[features]
memories = false
enable_request_compression = true
shell_snapshot = true
multi_agent = true
plugins = false
js_repl = false

[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"

[mcp_servers.node_repl]
args = []
command = "/opt/codex-desktop/resources/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = ""
NODE_REPL_NODE_PATH = "/opt/codex-desktop/resources/node-runtime/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/home/czc/.codex"
CODEX_HOME = "/home/czc/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "496c7b3cb95b4bc20cff49b513150606e0da0000c92bf752206bee5a6c248423,c69702d945f8bf56a4a529c4e6ded337b12d40203a3ada637870cceff8d4b900,fc05eca603616d74db7ac587851a19a66d94608533741186c1251f540c5835cd"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
BROWSER_USE_MARKETPLACE_NAME = "openai-bundled"
NODE_REPL_UNTRUSTED_ENV_ALLOWLIST = "BROWSER_USE_MARKETPLACE_NAME"

[notice]
hide_rate_limit_model_nudge = true

[notice.model_migrations]
"gpt-5.1-codex-mini" = "gpt-5.4"

[marketplaces.openai-bundled]
last_updated = "2026-06-25T03:17:18Z"
source_type = "local"
source = "/home/czc/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-06-25T03:46:47Z"
source_type = "local"
source = "/home/czc/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."read-aloud@openai-bundled"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[desktop]
conversationDetailMode = "STEPS_COMMANDS"
ambient-suggestions-enabled = false
